### PR TITLE
Fix sleeper draftpicks

### LINKED ISSUE #352: ff_draftpicks returning Error
**Describe the bug**
When calling ff_draftpicks for a sleeper league in 2022 I am getting an error related to the 'metadata column' (see image) 

**Reprex**
Please provide a short, reproducible example of the code you are trying to run. 

```r
ssb <- ff_connect(platform = "sleeper", league_id = "784453846419283968", season = 2022)
```
**Expected behavior**
I expected a table to return with users and their corresponding draft capital from sleeper api. 

**Session information**
Please copy the output of `sessionInfo()` into the box below.
```r
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ffscrapr_1.4.7.02

loaded via a namespace (and not attached):
 [1] compiler_4.0.5    pillar_1.7.0      prettyunits_1.1.1 remotes_2.4.0    
 [5] tools_4.0.5       pkgbuild_1.2.0    jsonlite_1.8.0    memoise_2.0.1    
 [9] lifecycle_1.0.1   tibble_3.1.6      pkgconfig_2.0.3   rlang_1.0.2      
[13] DBI_1.1.1         cli_3.2.0         rstudioapi_0.13   curl_4.3.2       
[17] xfun_0.23         fastmap_1.1.0     withr_2.4.2       httr_1.4.2       
[21] dplyr_1.0.8       generics_0.1.2    vctrs_0.4.0       rprojroot_2.0.2  
[25] tidyselect_1.1.2  glue_1.6.2        R6_2.5.1          processx_3.5.2   
[29] fansi_1.0.3       tidyr_1.2.0       callr_3.7.0       ratelimitr_0.4.1 
[33] purrr_0.3.4       magrittr_2.0.3    ps_1.6.0          ellipsis_0.3.2   
[37] assertthat_0.2.1  tinytex_0.32      utf8_1.2.2        cachem_1.0.6     
[41] crayon_1.5.1    ```

**Screenshots**

**Additional context**
Add any other context about the problem here.
![Screen Shot 2022-04-11 at 8 53 42 PM](https://user-images.githubusercontent.com/86253003/162856888-d58acf01-cb71-4004-9165-0bc9c8262282.png)

### PR DESCRIPTION
**Pull request by joeflan**
Fixes #352

`ff_draftpicks` is returning an error when trying to load sleeper data. It seems the current_picks object was removed

### CODE REVIEW

**Comment by joeflan** [comment]
I've done some local testing and it's all working now. 

`ff_draftpicks` returns a data frame now for the current upcoming draft. I've also tested the issue in #352 and can't reproduce. What's likely happening is their API was updated to the new league year and it is no longer an issue.

**Comment by tanho63** [comment]
Checks are being a pain in the butt. Are you good to use your branch version til I can look at it properly?

**Comment by joeflan** [comment]
Yeah I have no problem using my branch as the ffscraper package locally. Don't sweat it

**Comment by tanho63** [comment]
Okay, reviewing a little more closely now that I'm back. 

ff_draftpicks is designed to return the following:
- for the current-season, it should return the numeric-indexed picks (i.e. 1.01, 2.12, 3.01 etc) that have not yet been drafted (and should incorporate trades)
- for future seasons, it should return future picks by round

Sleeper used to make the former available but now only makes it available if the league is actively drafting - otherwise it only makes the traded picks available and (sometimes) a draft order. 

To recreate the previous functionality, I envision sleeper_draftpicks to need to do:

- check status of draft and whether a draft order is available. 
- if draft order is not avail, treat as future picks
- if draft order is avail, build pick order from draft order and draft type then apply pick trades, if any. 
- then run ff_draft and see if there's any selected picks to remove
- then bind onto the existing future drafts

**Comment by tanho63** [comment]
I'm trying to button up all these things this week before I get going on newjob so I should have some time to look at this today/tomorrow.

**Comment by tanho63** [comment]
Going to accept this PR so that ff_draftpicks is not entirely broken and open a new issue (#386) for the optimal behaviour.

**Pull request merged**
