### PR TITLE
Fix max week in `ff_starters()` (ESPN)

### PR DESCRIPTION
**Pull request by tonyelhabr**
Given the logic for [`ff_starters()` for Sleeper](https://github.com/ffverse/ffscrapr/blob/88d3e5148e95ec99c2db93422834cf3f21e670a8/R/sleeper_starters.R#L26) and the fact that I can't retrieve week 18 starter scores for my league last year (yes, we play through week 18 for some reason), I think `< max week` should be `<= max week`.

### CODE REVIEW

**Review by tanho63 — APPROVED** [review]
_shakes head_ LGTM 😆

**Comment by tonyelhabr** [comment]
silly me thinking that would work without running tests locally

**Comment by tonyelhabr** [comment]
> silly me thinking that would work without running tests locally

wait, i believe we just need to update the cache GitHub release (rebuild and add week 18 data), like was done last time. no rush on this.

**Pull request merged**
